version: 0.2

phases:
  pre_build:
    commands:
      - npm i --legacy-peer-deps
  build:
    commands:
      - npm run build $CONFIGURATION

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/kumar-world-frontend
